In [ ]:
import numpy as np
import pandas as pd
import os

In [ ]:
os.listdir('/content/drive/MyDrive/chest_xray/train/PNEUMONIA')[:5]

['person1180_virus_2010.jpeg',
 'person1230_virus_2081.jpeg',
 'person1513_virus_2632.jpeg',
 'person124_virus_238.jpeg',
 'person746_virus_1369.jpeg']

In [ ]:
os.listdir('/content/drive/MyDrive/chest_xray/train/NORMAL')[:5]

['NORMAL2-IM-0771-0001.jpeg',
 'NORMAL2-IM-1294-0001-0002.jpeg',
 'IM-0675-0001.jpeg',
 'NORMAL2-IM-1169-0001.jpeg',
 'IM-0421-0001.jpeg']

In [ ]:
from matplotlib import image
from PIL import Image
import os
import numpy as np
import pandas as pd

def Load_Images(path):
    folders = os.listdir(path)
    data = []
    label = []
    print(folders)

    if '.DS_Store' in folders:
        folders.remove('.DS_Store')

    print(folders)

    for i in folders:
        c = 0
        images = os.listdir(path+'/'+i)

        if '.DS_Store' in images:
            images.remove('.DS_Store')

        for j in images:
            c += 1

            im = Image.open(path+'/'+i+'/'+j).convert('RGB')
            im = im.resize((50, 50), image.NEAREST)

            ar = np.array(im)
            # print(ar.shape)
            data.append(ar)

            if i == 'NORMAL':
                label.append(i)
            else:
                label.append(j.split('_')[1])

        # print(c)

    t = pd.factorize(np.array(label))
    print(t)
    # print(tead())
    tgt = t[0]
    # print(len(images), len(label))
    return np.array(data), tgt



In [ ]:
os.listdir('/content/drive/MyDrive/chest_xray/train')

['PNEUMONIA', 'NORMAL', '.DS_Store']

In [ ]:
train_x,train_y=Load_Images('/content/drive/MyDrive/chest_xray/train')

['PNEUMONIA', 'NORMAL', '.DS_Store']
['PNEUMONIA', 'NORMAL']
(array([0, 0, 0, ..., 2, 2, 2]), array(['virus', 'bacteria', 'NORMAL'], dtype='<U8'))


In [ ]:
train_x.shape,train_y.shape

((5216, 50, 50, 3), (5216,))

In [ ]:
act='relu'
from keras.models import Sequential
from keras.layers import Conv2D,Dense, Flatten, MaxPooling2D, Dropout
model = Sequential()
model.add(Conv2D(50,(3,3),activation = act, input_shape = train_x.shape[1:]))
model.add(MaxPooling2D((2,2)))
model.add(Conv2D(60,(3,3),activation = act))
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.2))
model.add(Conv2D(80,(3,3),activation = act))
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.2))
model.add(Conv2D(160,(3,3),activation = act))
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(320,activation=act))
model.add(Dense(3,activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 48, 48, 50)        1400      
                                                                 
 max_pooling2d (MaxPooling2  (None, 24, 24, 50)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 22, 22, 60)        27060     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 11, 11, 60)        0         
 g2D)                                                            
                                                                 
 dropout (Dropout)           (None, 11, 11, 60)        0         
                                                                 
 conv2d_2 (Conv2D)           (None, 9, 9, 80)          4

In [ ]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(train_x, train_y, epochs=100)

Epoch 1/100
163/163 [==============================] - 17s 94ms/step - loss: 1.5736 - accuracy: 0.5447
Epoch 2/100
163/163 [==============================] - 15s 93ms/step - loss: 0.8457 - accuracy: 0.6227
Epoch 3/100
163/163 [==============================] - 15s 90ms/step - loss: 0.7251 - accuracy: 0.6869
Epoch 4/100
163/163 [==============================] - 15s 93ms/step - loss: 0.6829 - accuracy: 0.7076
Epoch 5/100
163/163 [==============================] - 15s 90ms/step - loss: 0.6191 - accuracy: 0.7337
Epoch 6/100
163/163 [==============================] - 15s 94ms/step - loss: 0.5776 - accuracy: 0.7498
Epoch 7/100
163/163 [==============================] - 15s 90ms/step - loss: 0.5569 - accuracy: 0.7634
Epoch 8/100
163/163 [==============================] - 16s 95ms/step - loss: 0.5698 - accuracy: 0.7506
Epoch 9/100
163/163 [==============================] - 15s 91ms/step - loss: 0.5490 - accuracy: 0.7636
Epoch 10/100
163/163 [==============================] - 15s 93ms/step - l

In [ ]:
test_x,test_y=Load_Images('/content/drive/MyDrive/chest_xray/test')

['PNEUMONIA', 'NORMAL']
['PNEUMONIA', 'NORMAL']
(array([0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
  

In [ ]:
model.evaluate(test_x,test_y)

20/20 [==============================] - 1s 24ms/step - loss: 1.1186 - accuracy: 0.7212


[1.1186392307281494, 0.7211538553237915]

In [ ]:
model.metrics_names

['loss', 'accuracy']

In [ ]:
act='relu'
from keras.models import Sequential
from keras.layers import Conv2D,Dense, Flatten, MaxPooling2D, Dropout
model = Sequential()
model.add(Conv2D(50,(3,3),activation = act, input_shape = train_x.shape[1:]))
model.add(MaxPooling2D((2,2)))
model.add(Conv2D(60,(3,3),activation = act))
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.2))
model.add(Conv2D(80,(3,3),activation = act))
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.2))
model.add(Conv2D(160,(3,3),activation = act))
model.add(MaxPooling2D((2,2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(320,activation=act))
model.add(Dense(3,activation='softmax'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 48, 48, 50)        1400      
                                                                 
 max_pooling2d_4 (MaxPoolin  (None, 24, 24, 50)        0         
 g2D)                                                            
                                                                 
 conv2d_5 (Conv2D)           (None, 22, 22, 60)        27060     
                                                                 
 max_pooling2d_5 (MaxPoolin  (None, 11, 11, 60)        0         
 g2D)                                                            
                                                                 
 dropout_3 (Dropout)         (None, 11, 11, 60)        0         
                                                                 
 conv2d_6 (Conv2D)           (None, 9, 9, 80)         

In [ ]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='nadam', metrics=['accuracy'])
model.fit(train_x, train_y, epochs=75)

Epoch 1/75
163/163 [==============================] - 18s 96ms/step - loss: 1.3207 - accuracy: 0.5656
Epoch 2/75
163/163 [==============================] - 16s 100ms/step - loss: 0.7198 - accuracy: 0.6729
Epoch 3/75
163/163 [==============================] - 17s 101ms/step - loss: 0.6252 - accuracy: 0.7224
Epoch 4/75
163/163 [==============================] - 16s 99ms/step - loss: 0.5798 - accuracy: 0.7487
Epoch 5/75
163/163 [==============================] - 16s 97ms/step - loss: 0.5463 - accuracy: 0.7623
Epoch 6/75
163/163 [==============================] - 16s 96ms/step - loss: 0.5183 - accuracy: 0.7736
Epoch 7/75
163/163 [==============================] - 15s 93ms/step - loss: 0.5033 - accuracy: 0.7830
Epoch 8/75
163/163 [==============================] - 15s 95ms/step - loss: 0.4932 - accuracy: 0.7851
Epoch 9/75
163/163 [==============================] - 15s 93ms/step - loss: 0.4825 - accuracy: 0.7885
Epoch 10/75
163/163 [==============================] - 15s 94ms/step - loss: 0.4

In [ ]:
test_x,test_y=Load_Images('/content/drive/MyDrive/chest_xray/test')

['PNEUMONIA', 'NORMAL', '.DS_Store']
['PNEUMONIA', 'NORMAL']
(array([0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0

In [ ]:
model.evaluate(test_x,test_y)

20/20 [==============================] - 1s 25ms/step - loss: 1.5261 - accuracy: 0.7051


[1.5260964632034302, 0.7051281929016113]

In [ ]:
model.metrics_names

['loss', 'accuracy']